// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/organizationmember"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/predicate"
	"github.com/google/uuid"
)

// OrganizationMemberUpdate is the builder for updating OrganizationMember entities.
type OrganizationMemberUpdate struct {
	config
	hooks    []Hook
	mutation *OrganizationMemberMutation
}

// Where appends a list predicates to the OrganizationMemberUpdate builder.
func (_u *OrganizationMemberUpdate) Where(ps ...predicate.OrganizationMember) *OrganizationMemberUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *OrganizationMemberUpdate) SetOrganizationID(v uuid.UUID) *OrganizationMemberUpdate {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *OrganizationMemberUpdate) SetNillableOrganizationID(v *uuid.UUID) *OrganizationMemberUpdate {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OrganizationMemberUpdate) SetUserID(v uuid.UUID) *OrganizationMemberUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OrganizationMemberUpdate) SetNillableUserID(v *uuid.UUID) *OrganizationMemberUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *OrganizationMemberUpdate) SetRole(v string) *OrganizationMemberUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *OrganizationMemberUpdate) SetNillableRole(v *string) *OrganizationMemberUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrganizationMemberUpdate) SetUpdatedAt(v time.Time) *OrganizationMemberUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OrganizationMemberMutation object of the builder.
func (_u *OrganizationMemberUpdate) Mutation() *OrganizationMemberMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrganizationMemberUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrganizationMemberUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrganizationMemberUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrganizationMemberUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrganizationMemberUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := organizationmember.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrganizationMemberUpdate) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := organizationmember.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "OrganizationMember.role": %w`, err)}
		}
	}
	return nil
}

func (_u *OrganizationMemberUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(organizationmember.Table, organizationmember.Columns, sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrganizationID(); ok {
		_spec.SetField(organizationmember.FieldOrganizationID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(organizationmember.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(organizationmember.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(organizationmember.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organizationmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrganizationMemberUpdateOne is the builder for updating a single OrganizationMember entity.
type OrganizationMemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrganizationMemberMutation
}

// SetOrganizationID sets the "organization_id" field.
func (_u *OrganizationMemberUpdateOne) SetOrganizationID(v uuid.UUID) *OrganizationMemberUpdateOne {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *OrganizationMemberUpdateOne) SetNillableOrganizationID(v *uuid.UUID) *OrganizationMemberUpdateOne {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OrganizationMemberUpdateOne) SetUserID(v uuid.UUID) *OrganizationMemberUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OrganizationMemberUpdateOne) SetNillableUserID(v *uuid.UUID) *OrganizationMemberUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *OrganizationMemberUpdateOne) SetRole(v string) *OrganizationMemberUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *OrganizationMemberUpdateOne) SetNillableRole(v *string) *OrganizationMemberUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrganizationMemberUpdateOne) SetUpdatedAt(v time.Time) *OrganizationMemberUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OrganizationMemberMutation object of the builder.
func (_u *OrganizationMemberUpdateOne) Mutation() *OrganizationMemberMutation {
	return _u.mutation
}

// Where appends a list predicates to the OrganizationMemberUpdate builder.
func (_u *OrganizationMemberUpdateOne) Where(ps ...predicate.OrganizationMember) *OrganizationMemberUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrganizationMemberUpdateOne) Select(field string, fields ...string) *OrganizationMemberUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OrganizationMember entity.
func (_u *OrganizationMemberUpdateOne) Save(ctx context.Context) (*OrganizationMember, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrganizationMemberUpdateOne) SaveX(ctx context.Context) *OrganizationMember {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrganizationMemberUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrganizationMemberUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrganizationMemberUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := organizationmember.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrganizationMemberUpdateOne) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := organizationmember.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "OrganizationMember.role": %w`, err)}
		}
	}
	return nil
}

func (_u *OrganizationMemberUpdateOne) sqlSave(ctx context.Context) (_node *OrganizationMember, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(organizationmember.Table, organizationmember.Columns, sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrganizationMember.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, organizationmember.FieldID)
		for _, f := range fields {
			if !organizationmember.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != organizationmember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrganizationID(); ok {
		_spec.SetField(organizationmember.FieldOrganizationID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(organizationmember.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(organizationmember.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(organizationmember.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &OrganizationMember{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organizationmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
