// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Servora-Kit/servora-iam/app/iam/service/internal/data/ent/application"
	"github.com/Servora-Kit/servora-iam/app/iam/service/internal/data/ent/user"
	"github.com/Servora-Kit/servora-iam/app/iam/service/internal/data/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	applicationFields := schema.Application{}.Fields()
	_ = applicationFields
	// applicationDescClientID is the schema descriptor for client_id field.
	applicationDescClientID := applicationFields[1].Descriptor()
	// application.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	application.ClientIDValidator = applicationDescClientID.Validators[0].(func(string) error)
	// applicationDescClientSecretHash is the schema descriptor for client_secret_hash field.
	applicationDescClientSecretHash := applicationFields[2].Descriptor()
	// application.ClientSecretHashValidator is a validator for the "client_secret_hash" field. It is called by the builders before save.
	application.ClientSecretHashValidator = applicationDescClientSecretHash.Validators[0].(func(string) error)
	// applicationDescName is the schema descriptor for name field.
	applicationDescName := applicationFields[3].Descriptor()
	// application.NameValidator is a validator for the "name" field. It is called by the builders before save.
	application.NameValidator = applicationDescName.Validators[0].(func(string) error)
	// applicationDescApplicationType is the schema descriptor for application_type field.
	applicationDescApplicationType := applicationFields[7].Descriptor()
	// application.DefaultApplicationType holds the default value on creation for the application_type field.
	application.DefaultApplicationType = applicationDescApplicationType.Default.(string)
	// application.ApplicationTypeValidator is a validator for the "application_type" field. It is called by the builders before save.
	application.ApplicationTypeValidator = applicationDescApplicationType.Validators[0].(func(string) error)
	// applicationDescAccessTokenType is the schema descriptor for access_token_type field.
	applicationDescAccessTokenType := applicationFields[8].Descriptor()
	// application.DefaultAccessTokenType holds the default value on creation for the access_token_type field.
	application.DefaultAccessTokenType = applicationDescAccessTokenType.Default.(string)
	// application.AccessTokenTypeValidator is a validator for the "access_token_type" field. It is called by the builders before save.
	application.AccessTokenTypeValidator = applicationDescAccessTokenType.Validators[0].(func(string) error)
	// applicationDescType is the schema descriptor for type field.
	applicationDescType := applicationFields[9].Descriptor()
	// application.DefaultType holds the default value on creation for the type field.
	application.DefaultType = applicationDescType.Default.(string)
	// application.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	application.TypeValidator = applicationDescType.Validators[0].(func(string) error)
	// applicationDescIDTokenLifetime is the schema descriptor for id_token_lifetime field.
	applicationDescIDTokenLifetime := applicationFields[10].Descriptor()
	// application.DefaultIDTokenLifetime holds the default value on creation for the id_token_lifetime field.
	application.DefaultIDTokenLifetime = applicationDescIDTokenLifetime.Default.(int)
	// applicationDescCreatedAt is the schema descriptor for created_at field.
	applicationDescCreatedAt := applicationFields[11].Descriptor()
	// application.DefaultCreatedAt holds the default value on creation for the created_at field.
	application.DefaultCreatedAt = applicationDescCreatedAt.Default.(func() time.Time)
	// applicationDescUpdatedAt is the schema descriptor for updated_at field.
	applicationDescUpdatedAt := applicationFields[12].Descriptor()
	// application.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	application.DefaultUpdatedAt = applicationDescUpdatedAt.Default.(func() time.Time)
	// application.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	application.UpdateDefaultUpdatedAt = applicationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// applicationDescID is the schema descriptor for id field.
	applicationDescID := applicationFields[0].Descriptor()
	// application.DefaultID holds the default value on creation for the id field.
	application.DefaultID = applicationDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[3].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescPhone is the schema descriptor for phone field.
	userDescPhone := userFields[4].Descriptor()
	// user.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	user.PhoneValidator = userDescPhone.Validators[0].(func(string) error)
	// userDescPhoneVerified is the schema descriptor for phone_verified field.
	userDescPhoneVerified := userFields[5].Descriptor()
	// user.DefaultPhoneVerified holds the default value on creation for the phone_verified field.
	user.DefaultPhoneVerified = userDescPhoneVerified.Default.(bool)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[6].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// user.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	user.RoleValidator = userDescRole.Validators[0].(func(string) error)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[7].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
	// user.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	user.StatusValidator = userDescStatus.Validators[0].(func(string) error)
	// userDescEmailVerified is the schema descriptor for email_verified field.
	userDescEmailVerified := userFields[8].Descriptor()
	// user.DefaultEmailVerified holds the default value on creation for the email_verified field.
	user.DefaultEmailVerified = userDescEmailVerified.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[11].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[12].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
