// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/predicate"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/tenant"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/tenantmember"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/user"
	"github.com/google/uuid"
)

// TenantMemberUpdate is the builder for updating TenantMember entities.
type TenantMemberUpdate struct {
	config
	hooks    []Hook
	mutation *TenantMemberMutation
}

// Where appends a list predicates to the TenantMemberUpdate builder.
func (_u *TenantMemberUpdate) Where(ps ...predicate.TenantMember) *TenantMemberUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *TenantMemberUpdate) SetTenantID(v uuid.UUID) *TenantMemberUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TenantMemberUpdate) SetNillableTenantID(v *uuid.UUID) *TenantMemberUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TenantMemberUpdate) SetUserID(v uuid.UUID) *TenantMemberUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TenantMemberUpdate) SetNillableUserID(v *uuid.UUID) *TenantMemberUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *TenantMemberUpdate) SetRole(v tenantmember.Role) *TenantMemberUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *TenantMemberUpdate) SetNillableRole(v *tenantmember.Role) *TenantMemberUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantMemberUpdate) SetStatus(v tenantmember.Status) *TenantMemberUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TenantMemberUpdate) SetNillableStatus(v *tenantmember.Status) *TenantMemberUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetJoinedAt sets the "joined_at" field.
func (_u *TenantMemberUpdate) SetJoinedAt(v time.Time) *TenantMemberUpdate {
	_u.mutation.SetJoinedAt(v)
	return _u
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_u *TenantMemberUpdate) SetNillableJoinedAt(v *time.Time) *TenantMemberUpdate {
	if v != nil {
		_u.SetJoinedAt(*v)
	}
	return _u
}

// ClearJoinedAt clears the value of the "joined_at" field.
func (_u *TenantMemberUpdate) ClearJoinedAt() *TenantMemberUpdate {
	_u.mutation.ClearJoinedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantMemberUpdate) SetUpdatedAt(v time.Time) *TenantMemberUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *TenantMemberUpdate) SetTenant(v *Tenant) *TenantMemberUpdate {
	return _u.SetTenantID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *TenantMemberUpdate) SetUser(v *User) *TenantMemberUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the TenantMemberMutation object of the builder.
func (_u *TenantMemberUpdate) Mutation() *TenantMemberMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *TenantMemberUpdate) ClearTenant() *TenantMemberUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TenantMemberUpdate) ClearUser() *TenantMemberUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenantMemberUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantMemberUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenantMemberUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantMemberUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantMemberUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenantmember.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantMemberUpdate) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := tenantmember.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "TenantMember.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := tenantmember.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TenantMember.status": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantMember.tenant"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantMember.user"`)
	}
	return nil
}

func (_u *TenantMemberUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenantmember.Table, tenantmember.Columns, sqlgraph.NewFieldSpec(tenantmember.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(tenantmember.FieldRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenantmember.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.JoinedAt(); ok {
		_spec.SetField(tenantmember.FieldJoinedAt, field.TypeTime, value)
	}
	if _u.mutation.JoinedAtCleared() {
		_spec.ClearField(tenantmember.FieldJoinedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantmember.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmember.TenantTable,
			Columns: []string{tenantmember.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmember.TenantTable,
			Columns: []string{tenantmember.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmember.UserTable,
			Columns: []string{tenantmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmember.UserTable,
			Columns: []string{tenantmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenantMemberUpdateOne is the builder for updating a single TenantMember entity.
type TenantMemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenantMemberMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *TenantMemberUpdateOne) SetTenantID(v uuid.UUID) *TenantMemberUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TenantMemberUpdateOne) SetNillableTenantID(v *uuid.UUID) *TenantMemberUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TenantMemberUpdateOne) SetUserID(v uuid.UUID) *TenantMemberUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TenantMemberUpdateOne) SetNillableUserID(v *uuid.UUID) *TenantMemberUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *TenantMemberUpdateOne) SetRole(v tenantmember.Role) *TenantMemberUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *TenantMemberUpdateOne) SetNillableRole(v *tenantmember.Role) *TenantMemberUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantMemberUpdateOne) SetStatus(v tenantmember.Status) *TenantMemberUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TenantMemberUpdateOne) SetNillableStatus(v *tenantmember.Status) *TenantMemberUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetJoinedAt sets the "joined_at" field.
func (_u *TenantMemberUpdateOne) SetJoinedAt(v time.Time) *TenantMemberUpdateOne {
	_u.mutation.SetJoinedAt(v)
	return _u
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_u *TenantMemberUpdateOne) SetNillableJoinedAt(v *time.Time) *TenantMemberUpdateOne {
	if v != nil {
		_u.SetJoinedAt(*v)
	}
	return _u
}

// ClearJoinedAt clears the value of the "joined_at" field.
func (_u *TenantMemberUpdateOne) ClearJoinedAt() *TenantMemberUpdateOne {
	_u.mutation.ClearJoinedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantMemberUpdateOne) SetUpdatedAt(v time.Time) *TenantMemberUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *TenantMemberUpdateOne) SetTenant(v *Tenant) *TenantMemberUpdateOne {
	return _u.SetTenantID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *TenantMemberUpdateOne) SetUser(v *User) *TenantMemberUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the TenantMemberMutation object of the builder.
func (_u *TenantMemberUpdateOne) Mutation() *TenantMemberMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *TenantMemberUpdateOne) ClearTenant() *TenantMemberUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TenantMemberUpdateOne) ClearUser() *TenantMemberUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the TenantMemberUpdate builder.
func (_u *TenantMemberUpdateOne) Where(ps ...predicate.TenantMember) *TenantMemberUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenantMemberUpdateOne) Select(field string, fields ...string) *TenantMemberUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TenantMember entity.
func (_u *TenantMemberUpdateOne) Save(ctx context.Context) (*TenantMember, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantMemberUpdateOne) SaveX(ctx context.Context) *TenantMember {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenantMemberUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantMemberUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantMemberUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenantmember.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantMemberUpdateOne) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := tenantmember.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "TenantMember.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := tenantmember.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TenantMember.status": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantMember.tenant"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantMember.user"`)
	}
	return nil
}

func (_u *TenantMemberUpdateOne) sqlSave(ctx context.Context) (_node *TenantMember, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenantmember.Table, tenantmember.Columns, sqlgraph.NewFieldSpec(tenantmember.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TenantMember.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenantmember.FieldID)
		for _, f := range fields {
			if !tenantmember.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenantmember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(tenantmember.FieldRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenantmember.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.JoinedAt(); ok {
		_spec.SetField(tenantmember.FieldJoinedAt, field.TypeTime, value)
	}
	if _u.mutation.JoinedAtCleared() {
		_spec.ClearField(tenantmember.FieldJoinedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantmember.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmember.TenantTable,
			Columns: []string{tenantmember.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmember.TenantTable,
			Columns: []string{tenantmember.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmember.UserTable,
			Columns: []string{tenantmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmember.UserTable,
			Columns: []string{tenantmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TenantMember{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
