// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Servora-Kit/servora/api/gen/go/conf/v1"
	conf2 "github.com/Servora-Kit/servora/api/gen/go/iam/conf/v1"
	"github.com/Servora-Kit/servora/app/iam/service/internal/biz"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data"
	"github.com/Servora-Kit/servora/app/iam/service/internal/server"
	"github.com/Servora-Kit/servora/app/iam/service/internal/service"
	"github.com/Servora-Kit/servora/pkg/bootstrap"
	"github.com/Servora-Kit/servora/pkg/governance/registry"
	"github.com/Servora-Kit/servora/pkg/governance/telemetry"
	"github.com/Servora-Kit/servora/pkg/jwks"
	"github.com/Servora-Kit/servora/pkg/openfga"
	"github.com/Servora-Kit/servora/pkg/transport/client"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, discovery *conf.Discovery, confRegistry *conf.Registry, confData *conf.Data, app *conf.App, trace *conf.Trace, metrics *conf.Metrics, mail *conf.Mail, confBiz *conf2.Biz, svcIdentity bootstrap.SvcIdentity, logger log.Logger) (*kratos.App, func(), error) {
	registrar := registry.NewRegistrar(confRegistry)
	telemetryMetrics, err := telemetry.NewMetrics(metrics, app, logger)
	if err != nil {
		return nil, nil, err
	}
	keyManager, err := jwks.NewKeyManagerFromConfig(app)
	if err != nil {
		return nil, nil, err
	}
	openfgaClient := openfga.NewClientOptional(app, logger)
	redisClient, cleanup, err := data.NewRedis(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	driver, err := data.NewEntDriver(confData)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	entClient, err := data.NewDBClient(driver, app, confBiz, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	platformRootID, err := data.NewPlatformRootID(entClient, openfgaClient, confBiz, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	grpcMiddleware := server.NewGRPCMiddleware(trace, telemetryMetrics, logger, keyManager, openfgaClient, redisClient, platformRootID)
	registryDiscovery := registry.NewDiscovery(discovery)
	clientClient, err := client.NewClient(confData, trace, registryDiscovery, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	dataData, cleanup2, err := data.NewData(entClient, confData, logger, clientClient, redisClient)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	authnRepo := data.NewAuthnRepo(dataData, logger)
	otpRepo := data.NewOTPRepo(redisClient, logger)
	sender := data.NewMailSender(mail)
	organizationRepo := data.NewOrganizationRepo(dataData, logger)
	projectRepo := data.NewProjectRepo(dataData, logger)
	authZRepo := data.NewAuthZRepo(openfgaClient, redisClient)
	organizationUsecase := biz.NewOrganizationUsecase(organizationRepo, projectRepo, authZRepo, logger, platformRootID)
	projectUsecase := biz.NewProjectUsecase(projectRepo, organizationRepo, authZRepo, logger)
	authnUsecase := biz.NewAuthnUsecase(authnRepo, otpRepo, sender, mail, logger, app, keyManager, organizationUsecase, projectUsecase)
	authnService := service.NewAuthnService(authnUsecase)
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger, app, authnRepo, organizationRepo, projectRepo, authZRepo, platformRootID)
	userService := service.NewUserService(userUsecase)
	testRepo := data.NewTestRepo(dataData, logger)
	testUsecase := biz.NewTestUsecase(testRepo, logger)
	testService := service.NewTestService(testUsecase)
	organizationService := service.NewOrganizationService(organizationUsecase)
	projectService := service.NewProjectService(projectUsecase)
	grpcServer := server.NewGRPCServer(confServer, grpcMiddleware, logger, authnService, userService, testService, organizationService, projectService)
	httpMiddleware := server.NewHTTPMiddleware(trace, telemetryMetrics, logger, keyManager, openfgaClient, redisClient, platformRootID)
	handler := server.NewHealthHandler(redisClient, driver)
	httpServer := server.NewHTTPServer(confServer, app, httpMiddleware, telemetryMetrics, logger, handler, keyManager, authnService, userService, testService, organizationService, projectService)
	kratosApp := newApp(svcIdentity, logger, registrar, grpcServer, httpServer)
	return kratosApp, func() {
		cleanup2()
		cleanup()
	}, nil
}
